absolute-paths-allowed-crates = ["serde", "serde_json", "serde-jsonlines", "serde_yaml", "toml", "serde-xml-rs", "quick-xml", "anyhow", "reqwest", "url", "rust_decimal", "time"]
absolute-paths-max-segments = 2
