[lint]
extend-select = [
    "S001", # unquoted-argument-expansion
    "S002", # raw-input-backslash-preservation
    "S003", # loop-from-command-output
    "S004", # unquoted-command-substitution
    "S007", # printf-format-variable
    "S008", # unquoted-array-expansion
    "S009", # echoed-command-substitution
    "S010", # export-command-substitution
    "S011", # compound-test-operator
    "S012", # ps-grep-pipeline
    "S013", # ls-grep-pipeline
    "S014", # unquoted-dollar-star
    "S015", # quoted-dollar-star-loop
    "S017", # unquoted-array-split
    "S018", # command-output-array-split
    "S019", # grep-output-in-test
    "S021", # positional-args-in-string
    "S024", # single-quote-backslash
    "S028", # suspect-closing-quote
    "S030", # heredoc-end-space
    "S031", # trailing-directive
    "S033", # echo-here-doc
    "S036", # bare-read
    "S039", # literal-backslash-in-single-quotes
    "S040", # literal-control-escape
    "S043", # missing-shebang-line
    "S046", # ls-piped-to-xargs
    "S047", # ls-in-substitution
    "S049", # unquoted-tr-range
    "S051", # unquoted-tr-class
    "S052", # unquoted-variable-in-test
    "S054", # su-without-flag
    "S055", # glob-assigned-to-variable
    "S056", # command-substitution-in-alias
    "S057", # function-in-alias
    "S058", # unquoted-path-in-mkdir
    "S062", # default-value-in-colon-assign
    "S066", # local-declare-combined
    "S067", # leading-glob-in-grep-pattern
    "S068", # trap-signal-numbers
    "S069", # getopts-invalid-flag-handler
    "S070", # double-quote-nesting
    "S071", # env-prefix-command-only
    "S072", # linebreak-before-and
    "S073", # spaced-tabstrip-close
    "S074", # ampersand-semicolon
    "S077", # brace-variable-before-bracket
]
